// Generated by scripts/build-shotlist.mjs from docs/shot-list.json. Do not edit by hand.
export type ShotMode = "pulse" | "steel" | "calm" | "water" | "rim" | "street";
export const SHOT_META: Record<string, { mode: ShotMode; ratio: string }> = {
  "hero": {
    "mode": "pulse",
    "ratio": "16:9"
  },
  "hero-mobile": {
    "mode": "pulse",
    "ratio": "9:16"
  },
  "pulse-check": {
    "mode": "pulse",
    "ratio": "4:5"
  },
  "zone-gym-floor": {
    "mode": "steel",
    "ratio": "16:9"
  },
  "zone-functional": {
    "mode": "steel",
    "ratio": "3:2"
  },
  "zone-cardio": {
    "mode": "steel",
    "ratio": "3:2"
  },
  "zone-pool": {
    "mode": "water",
    "ratio": "3:2"
  },
  "zone-spa": {
    "mode": "calm",
    "ratio": "3:2"
  },
  "zone-lobby": {
    "mode": "steel",
    "ratio": "3:2"
  },
  "facade-night": {
    "mode": "street",
    "ratio": "16:9"
  },
  "zone-kids": {
    "mode": "calm",
    "ratio": "3:2"
  },
  "zone-lockers": {
    "mode": "calm",
    "ratio": "3:2"
  },
  "zone-fitbar": {
    "mode": "steel",
    "ratio": "3:2"
  },
  "studio-cycle": {
    "mode": "pulse",
    "ratio": "3:2"
  },
  "studio-ring": {
    "mode": "pulse",
    "ratio": "3:2"
  },
  "studio-forge": {
    "mode": "pulse",
    "ratio": "3:2"
  },
  "studio-dance": {
    "mode": "pulse",
    "ratio": "3:2"
  },
  "studio-yoga": {
    "mode": "calm",
    "ratio": "3:2"
  },
  "studio-reformer": {
    "mode": "calm",
    "ratio": "3:2"
  },
  "class-cycle": {
    "mode": "pulse",
    "ratio": "3:2"
  },
  "class-boxing": {
    "mode": "pulse",
    "ratio": "3:2"
  },
  "class-hiit": {
    "mode": "pulse",
    "ratio": "3:2"
  },
  "class-functional": {
    "mode": "steel",
    "ratio": "3:2"
  },
  "class-dance": {
    "mode": "pulse",
    "ratio": "3:2"
  },
  "class-yoga": {
    "mode": "calm",
    "ratio": "3:2"
  },
  "class-stretching": {
    "mode": "calm",
    "ratio": "3:2"
  },
  "class-reformer": {
    "mode": "calm",
    "ratio": "3:2"
  },
  "class-aqua": {
    "mode": "water",
    "ratio": "3:2"
  },
  "class-swim": {
    "mode": "water",
    "ratio": "3:2"
  },
  "class-strength": {
    "mode": "steel",
    "ratio": "3:2"
  },
  "class-run": {
    "mode": "steel",
    "ratio": "3:2"
  },
  "class-row": {
    "mode": "pulse",
    "ratio": "3:2"
  },
  "class-trx": {
    "mode": "steel",
    "ratio": "3:2"
  },
  "coach-boxing": {
    "mode": "rim",
    "ratio": "3:4"
  },
  "coach-cycle": {
    "mode": "rim",
    "ratio": "3:4"
  },
  "coach-strength": {
    "mode": "rim",
    "ratio": "3:4"
  },
  "coach-hiit": {
    "mode": "rim",
    "ratio": "3:4"
  },
  "coach-functional": {
    "mode": "rim",
    "ratio": "3:4"
  },
  "coach-yoga": {
    "mode": "rim",
    "ratio": "3:4"
  },
  "coach-mobility": {
    "mode": "rim",
    "ratio": "3:4"
  },
  "coach-pilates": {
    "mode": "rim",
    "ratio": "3:4"
  },
  "coach-swim": {
    "mode": "rim",
    "ratio": "3:4"
  },
  "coach-dance": {
    "mode": "rim",
    "ratio": "3:4"
  },
  "coach-running": {
    "mode": "rim",
    "ratio": "3:4"
  },
  "coach-head": {
    "mode": "rim",
    "ratio": "3:4"
  },
  "goal-lean": {
    "mode": "pulse",
    "ratio": "4:5"
  },
  "goal-endurance": {
    "mode": "pulse",
    "ratio": "4:5"
  },
  "goal-strength": {
    "mode": "steel",
    "ratio": "4:5"
  },
  "goal-health": {
    "mode": "calm",
    "ratio": "4:5"
  },
  "detail-rubber-floor": {
    "mode": "steel",
    "ratio": "1:1"
  },
  "detail-chalk": {
    "mode": "pulse",
    "ratio": "4:5"
  },
  "detail-hr-strap": {
    "mode": "pulse",
    "ratio": "1:1"
  },
  "detail-plates": {
    "mode": "steel",
    "ratio": "3:2"
  },
  "detail-towel-bottle": {
    "mode": "calm",
    "ratio": "1:1"
  },
  "detail-led-line": {
    "mode": "pulse",
    "ratio": "16:9"
  },
  "detail-wristband": {
    "mode": "pulse",
    "ratio": "1:1"
  },
  "empty-gym": {
    "mode": "pulse",
    "ratio": "16:9"
  }
};
